# Generated by Django 5.1.4 on 2024-12-31 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to='API.plant'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='API.site'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userplanttask',
            name='user_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='API.userplant'),
        ),
        migrations.AddField(
            model_name='tasktocheck',
            name='user_plant_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.userplanttask'),
        ),
    ]
