# Generated by Django 5.1.4 on 2024-12-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_site_userplant_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='API.site'),
        ),
    ]
