# Generated by Django 5.1.4 on 2025-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_plant_bloom_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tasktocheck',
            index=models.Index(fields=['completed_at'], name='API_tasktoc_complet_e976d9_idx'),
        ),
    ]
