# Generated by Django 5.1.4 on 2024-12-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_userplanttask_tasktocheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_plants/'),
        ),
    ]
